layout_spectrum: 1
typography_spectrum: 0.344086
color:
  saturation: 0.9209423
  lightness: 0.3714998
  brandStrength: 0
  brandColors:
    - '#FFFFFF'
    - '#5B80A3'
    - '#4C295B'
    - '#A3A37F'
    - '#E99A5B'
  rhythmicContrast: 0.149409
name: Josephbestjames
