name: Josephbestjames
favicon: null
layout_spectrum: 1
typography_spectrum: 0.344086
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#5B80A3'
    - '#4C295B'
    - '#A3A37F'
    - '#E99A5B'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
